apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.75.2/bundle.yaml
  - prometheus.yaml
  - service-account.yaml
  - monitor.yaml
