apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.26/deploy/local-path-storage.yaml
configMapGenerator:
- behavior: merge
  files:
  - config.json
  name: local-path-config
  namespace: local-path-storage
patches:
- path: namespace.yaml
- path: storage.yaml