apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colium-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BlockCat/k8s-nas.git
    targetRevision: master
    path: cilium
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      # prune: true
      # selfHeal: true
