apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glauth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BlockCat/k8s-nas.git
    targetRevision: master
    path: utils/glauth
  destination:
    server: https://kubernetes.default.svc
    namespace: glauth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
