apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-policy.yaml
  - ../argocd
  - traefik.application.yaml
  - immich.application.yaml
  - cloudflared.application.yaml
  # - cilium.application.yaml