apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BlockCat/k8s-nas.git
    targetRevision: master
    path: applications/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      # prune: true
      selfHeal: true
