apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: syncthing/syncthing:latest
          imagePullPolicy: Always
          command:
            - "/bin/syncthing"
          args:
            - "-home"
            - "/var/syncthing/config"
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: PUID
              value: "1001"
            - name: GUID
              value: "1001"
            - name: TZ
              value: "Europe/Amsterdam"
            - name: STGUIADDRESS
              value: ""
          ports:
            - containerPort: 8384
              name: http
              protocol: TCP
            - containerPort: 22000
              name: sync
              protocol: TCP
            - containerPort: 22000
              name: quic
              protocol: UDP
            - containerPort: 21027
              name: discovery
              protocol: UDP
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing
            - name: syncthing-data
              mountPath: /var/data
          livenessProbe: 
            tcpSocket:
              port: http
          readinessProbe: 
            tcpSocket:
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 300Mi
            
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-data
          persistentVolumeClaim:
            claimName: syncthing-data
