apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app: syncthing
spec:
  selector:
    app.kubernetes.io/name: syncthing
  ports:
    - name: http
      port: 8384
      targetPort: 8384
      protocol: TCP
    - name: sync
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: quic
      port: 22000
      targetPort: 22000
      protocol: UDP
    - name: discovery
      port: 21027
      targetPort: 21027
      protocol: UDP
