apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - ingress.yaml
  - ./cloudflare
helmCharts:
  name: traefik
  releaseName: traefik
  version: 25.0.0
  repo: https://traefik.github.io/charts