apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-policy
spec:
  # Default deny all traffic
  podSelector: 
    matchLabels:
      app: traefik-service
  policyTypes:
    - Ingress
    - Egress

  # ingress: {}
  # egress: {}
