# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: immich-dashboard-https
#   namespace: traefik
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`immich.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
#       kind: Rule
#       services:
#         - name: api@internal
#           kind: TraefikService
