apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - ingress.yaml
helmCharts:
  - name: immich
    releaseName: immich
    version: 0.2.0
    repo: https://immich-app.github.io/immich-charts
    valuesMerge: |
      postgresql:
        enabled: true
      redis:
        enabled: true
      typesense:
        enabled: true
      immich:
        persistence:
          library:
            existingClaim: immich-pvc
