apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: {}
# resources:
#   - ingress.yaml
helmCharts:
  - name: immich
    releaseName: immich
    version: 0.2.0
    repo: https://immich-app.github.io/immich-charts
