apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            [
              "sh",
              "-c",
              'ls /tmp/ovpn/ && cp /tmp/ovpn/* /etc/openvpn/custom/ && echo "Done" && ls /etc/openvpn/custom/',
            ]
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            # runAsUser: 1003
            # runAsGroup: 1003
            seccompProfile:
              type: Localhost
              localhostProfile: profiles/audit.json
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: transmission-ovpn
              mountPath: /tmp/ovpn/
            - name: transmission-ovpn-scratch
              mountPath: /etc/openvpn/custom
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:dev
          ports:
            - name: webinterface
              containerPort: 9091
          env:
            - name: OPENVPN_PROVIDER
              value: custom
            - name: OPENVPN_OPTS
              value: --inactive 3600 --ping 10 --ping-exit 60
            - name: LOCAL_NETWORK
              value: "192.168.178.0/24,10.244.0.0/16"
            - name: PUID
              value: "1003"
            - name: PGID
              value: "1003"
          envFrom:
            - secretRef:
                name: transmission-credentials
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 100
            successThreshold: 1
            exec:
              command:
                - bash
                - -c
                - "curl -s https://airvpn.org/api/whatismyip/ | jq -e '.airvpn == true'"
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 100
            successThreshold: 2
            exec:
              command:
                - bash
                - -c
                - "curl -s https://airvpn.org/api/whatismyip/ | jq -e '.airvpn == true'"
            timeoutSeconds: 60
          securityContext:
            runAsNonRoot: false
            # runAsUser: 1003
            # runAsGroup: 1003
            allowPrivilegeEscalation: false
            seccompProfile:
              type: Localhost
              localhostProfile: profiles/audit.json

            capabilities:
              # drop:
              #   - ALL
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1000Mi
          volumeMounts:
            - name: transmission-data
              mountPath: /data
            - name: transmission-config
              mountPath: /config
            - name: transmission-ovpn-scratch
              mountPath: /etc/openvpn/custom
        - image: ghcr.io/blockcat/transmission-exporter:master
          name: transmission-exporter
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - name: prom-scrape
              containerPort: 9190
          env:
            - name: TRANSMISSION_ADDR
              value: "http://localhost:9091"
            #  Uncomment these once you add authentication to transmission
            # - name: TRANSMISSION_USERNAME
            #   value: "transmission"
            # You can use a tool like `kontemplate` + `pass` to avoid hardcoding this in your repo
            # - name: TRANSMISSION_PASSWORD
            #   value: "hunter2"
            - name: WEB_PATH
              value: "/metrics"
            - name: WEB_ADDR
              value: ":9190"
      volumes:
        - name: transmission-data
          persistentVolumeClaim:
            claimName: transmission-pvc
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: transmission-ovpn
          secret:
            secretName: transmission-ovpn
        - name: transmission-ovpn-scratch
          emptyDir:
            sizeLimit: 50Mi
