apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - namespace.yaml
  - pvc.yaml
  - transmission-credentials.sealed.yaml
  - transmission-ovpn.sealed.yaml
  - deployment.yaml