apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: transmission
spec:
  ports:
    - port: 9091
      protocol: TCP
      targetPort: webinterface
      nodePort: 30000
  selector:
    app: transmission
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-metrics
  namespace: transmission
  labels:
    app: transmission-metrics
spec:
  ports:
    - port: 9190
      protocol: TCP
      targetPort: prom-scrape
      name: prom-scrape
  selector:
    app: transmission
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transmission-prometheus
  namespace: transmission
spec:
  selector:
    matchLabels:
      app: transmission-metrics
  endpoints:
    - port: prom-scrape
      interval: 10s
      path: /metrics
