apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    releaseName: cilium
    version: 1.14.4
    repo: https://helm.cilium.io/
    valuesInline:
      hubble:d
        relay:
          enable: true
        ui:
          enable: true