apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/install.yaml
  - argocd.yaml
  - ingress.yaml
  - repository.yaml
  - policy.yaml
configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--enable-helm