---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCQV5gGgAKZQKiFHWLFBAIQn2PfWqAKO6d7q3z8Yn4WNqPehHCp9rB6Stz63nTGzo8OMpE6hI223hYt7YNFQ1gLN3QWcb/qfpNvRAtntWvBpmqdMeHeX2azAa91I3sw7YRpx3Vvm8SjuI2jgd894Z90sc047t4zXz0cSQXBKAARLVmX1ToHD/H4bOzpzGlCX/8Crpom7dNxQqBhPKsq3CzSqu6wkfEYudTOX3KGlj7iRY0Yc9AjV6z5Jt0jZ+37SgO4SnbPIl423DX96cOHuRzUR6n6HvZTU+cYspkKwFtKAMp+8fnWAUE0IrNa/nW9VBkaXPO2ueTimqCItb/NoCkEHFZTvHQdf03Jy4nLtAaSUsXGh9n6rB18t9T0/tkm3yYiZ+1Z3G/aCFhKQprAEjd3FWXpr0UyUKbNSvASOw5VcZH208ROholcE1Kdlzy7b1+GgN9HLneJ81mYu+6EUKzp95SuO4dA/vFldolPk825xRbVpFBVQBOExhYIQRoC6jldwlCvji6mtDbI1kyyFLLnpjxfdzks/T7DEP9+jrAUDJp9hdep3xlIrrfhtvZR2yGxh8bhlibYWoqWtw3GDe/9ZQxQcR5F0rOojqNNDEkDcD/+lxAO++fOFnmzqb9a4+mZh5gc7h4iw33yCMDd7lXkbBULFmKv2cnlcI/8PH6tnKm0627LegX6Ed14fuTmRDV5LJjoNgakPnNU7Of5pVFJ8AbPEAvQShaKPEGy18bj/uqzJ3gYIvzu71gtGTBFrEyVBqtlQ89zGmMGzq1kuyYI9Bmza0kHenF+FpXivO8Gq9jWewC5nf5KUNin3yLwZs9qpCn1ifJF6ZDNh1MrBKFkCuGlotua/rEQXcRFWlQq3wajBQMEf8QrskubT2TgzL+8Qk4Tco6qbl53edFO/E0MpAvrSTaEKpI6K4zBkYXjwe0TFn9+yJCb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflared
