---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAUwIaqV377+h/85fWwo8GnUbW7qYTsAKCBez+wuAw3EuyUO0JWC/LbndPF4OVOGEk2tnpGBCWgt7/gHiGv3h4UxOyylqfv1Pnh5zwxOHbDE3yohgy763S9dF92K3d7L6hRtSvE+SZQ0xXMX1JCjs3PDEnunsGq/R54uR9nW4flbF09SPYAvbewSK4GztMHVStb0C/KWQYQN79c1L196yBJuW0Cxj/f6z6nATlz588zZSSxDZ7yAysZqo7pGiEec/SiqFLCgH1vxKoD8WzPDmXWzCSypDAzHJDujcA0cE99gbRk5UTlqy2Jc2kxngQH2FUtyzXzZyov3SvsOJbbB0i3b8fTupaNjBPE28JZTeP19zu8ulaWYw9ILZZvRPdQrcMA9WHCD5XDC+2ihLoNEHjbcEn3poYXdpBVCVEBdz4HUudwExE5btyLZZNlZzTg4KMg2VwQTDrZ5kcWI4xdCh3dhbWngiaYdUYFp+FOze2EItgC+Lf5GbBj9iynxUAazypr69oWQD7k3xB6uWLwP3M/nVsRFA8R7U8yzBwZvcKPDsmjWYOQGZAgV/fvq1M35quAErQzSIFWNcWdq/9g+iW7Ik/QDIT3z9NyYKY8igqAnFa9/EV4bNRrSkOaE8LVUgqvM647sXCoi1O5cC/RGa4D7J2zv/ObXwZBzJJOUJBcYWRvBPBuYTzjJYjUbpsEKIETVZJEOg21+cY+nexCfopEhz+ZzVDZNw41/t4I0pQad4cAJyvdcJtlCIgz3lUpT8wPdPcjJ4IWHeV7wVfWmAAXSGmzUBBIETnRvSBltYNqhGc8tuatDRePGxxyQhaLYeR25H+VL21/fhW45TYm/nE6e9lvWedoFsll/ho6OND1b8rEyH0P0x6WLnLNeGjxqL9BFnLZ80ljzR+M5IAf0RiSpiYuLBHoPLJVY2XRpvtLn5gYDpRSAkli
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflared
