apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: cloudflared
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  policyTypes:
    - Egress
  # egress:
  #  - {}
  # - to:
  #   - namespaceSelector:
  #       matchLabels:
  #         name: argocd
  #   - podSelector:
  #       matchLabels:
  #         name: argocd-server
