apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-sa
  namespace: cloudflare
---
apiVersion: v1
kind: Role
metadata:
  name: cloudflare-role
  namespace: cloudflare
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudflare-rb
  namespace: cloudflare
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudflare-role
subjects:
  - kind: ServiceAccount
    name: cloudflare-sa
    namespace: cloudflare
