apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/install.yaml
  - argocd.application.yaml
  - repositories.yaml
  - ldap-secret.sealed.yaml
configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    # Insecure because of cloudflared proxy
    literals:
      - server.insecure=true
  - name: argocd-cm
    behavior: merge    
    literals:
      - kustomize.buildOptions=--enable-helm
      - url=https://argocd.onomiwo.nl
      - accounts.blockcat=apiKey, login
      - admin.enabled=false
  - name: argocd-cm
    behavior: merge
    files:
      - dex.config
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.default=role:readonly
  - name: argocd-rbac-cm
    behavior: merge
    files:
      - policy.csv