---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-secret
  namespace: argocd
spec:
  encryptedData:
    dex.ldap.bindDN: AgCfyJ1aM8JKoWoLoYFQmyn4w4kK/mULrKsVuzIk2v3vLXfWcRJ0qKGrYK3fNjxPG6sOBhz4mLEvPf7GKT2v9mbhJSmw7CQuicoCNiEs0YkF8hdZ6A7V6I9WGTCnYUR5wExPdhJHxK9z9bCl3viQJCBQQ2Iqr4F2tSYI1+d4YPrHCeYG3DCG1UXYOe1sXzmd02q/p3fuvuWsN4e0ZZDHmVQBDVjKTL3D7Ei16oHsWHHN57dxxxaEsypKk5tCqKicJezLiqu8d7M3tUQegQAIq536zJ8NRkZ1bT4TnP4TzXWqel2gBgW3cmyuxYRp51HXDiccPO4JNH6X2qbzM45oZD/OWEWvITdgs+QZgD19ajAZ/5Oa1XvNqow0+2zTB58LPHBnVXUO5C2urP4ImEa1RgA4ORO8CnM41Zm0q5Hwc7MQ0gC6FwrCXBSAZbn7GVoBMIUdI82FlBC2nElWWpgxwWy/ts/3/+xyyMfosPuDQvDu13p3gcttQcQtElWir0sluHw7X8/dQEfV9ic3/w3jlzocP2tD9JIWwdMwFoZRwVh6xyGYSkkmJ9p5j46IcxLb+TuMYjTAN6O+yvXzz7Z6xhn6GuSi2waQGhlBrRpT6UUURCBmgs5cMcqrgsIVhAtmU6HsuO9Gc2OEeO2Q9jnAto7UTy5aoEPjr4S+6HB3NtAdssMinOmdWZjIV1bQkNOBpVl7Axp7PAIr5QsUWGa9lR0cmZeXd3k3agHV7Q1R
    dex.ldap.bindPW: AgB6GuNshf5azw3KWszSgroE/LT+0DPPNn0M3LTsdm44Hyv8Nq3/t1+Bteac1R6D/v/3fFSBbI1h+66KAgVJ1k4rNQ3L9LyptDzIHZusI1eusUVN7MBt+b+pwB8uM+0EYQeaa+TK2OaYvekSVEGn47NZ41bfM8jE5MEu4N0tzDBDfxqwE0vo9aSk0ORF5J9O9KRDdfqwTCiUnRCIfwvN9Eq8DIU5VtfN75zfdHpex1aZwrap8RwPZ27NAvuNLm2JCuqkgkHIJXeZGOggeMvhOv46ZvjQ7V0nZR1icCicbjC2hYoRSwLDHbfDx9SD/kW1Bn0LMXjtBJ1z4MsZ3Z4Po5QGUj3RzMITamJFO5mWUkwy6KLfYOpoTXWwe+Sbg0gQvR1ALGNhKuZkClhe46Hl7Qak2A9kAryQE5LcX3/mdG/rYCzLdL9j69hW8j46x45lI5CXI2dyTVL8iSrdpZmAqHWQh4Dsu+UmP3F6uYMYyFb6rZhV/CvLtU0aYnd6PRChUfvv+HJpCMW81e4Gcz/0ph/9HM2YXdVBb0VgXY4DhRyZt6ZzPMc+PF0RUB+xbzkaQ76mgakwxY6Bbd7wb4JW9cl1ow6k0ktMnWcct/u4aSsPYtnksG5lRPXw3nz2IAM6RQ1h0DAef623Uuuqu9KiW1ES46/6cxpJ50O+RtJzCG60X/ih4kaHotiKgbNMpBfxlMIF4DepjLwkQn9vW9/1wKUVDJxTjQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: ldap-secret
      namespace: argocd
