apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - ingress.yaml
helmCharts:
  - name: immich
    releaseName: immich
    version: 0.3.1
    repo: https://immich-app.github.io/immich-charts
    valuesMerge: override
    valuesInline:
      postgresql:
        enabled: true
      redis:
        enabled: true
      immich:
        persistence:
          library:
            existingClaim: immich-pvc
