apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - pvc.yaml
helmCharts:
  - name: immich
    releaseName: immich
    version: 0.3.1
    repo: https://immich-app.github.io/immich-charts
    valuesMerge: override
    valuesInline:
      postgresql:
        enabled: true
        primary:
          persistence:
            existingClaim: immich-pgsql-pvc
      redis:
        enabled: true
        master:
          persistence:
            existingClaim: immich-redis-pvc
      immich:
        persistence:
          library:
            existingClaim: immich-pvc
