apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glauth
resources:
  - namespace.yaml
  - deployment.yaml
  - users.secret.sealed.yaml
  - certs.yaml
  - monitor.yaml
configMapGenerator:
  - name: glauth-config
    options:
      disableNameSuffixHash: true
    files:
      - config.cfg